In [7]:
import numpy as np
import pandas
import matplotlib
import sklearn

In [49]:
mat_a =np.array([1,2,3,4,5,6,7,8])
mat_a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
mat_a.shape

(8,)

In [60]:
mat_a.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [68]:
# concatenate


a = np.array([2,2,2,2])
b = np.array([4,4,4,4])

c = np.concatenate((a,b))

In [69]:
a,b

(array([2, 2, 2, 2]), array([4, 4, 4, 4]))

In [70]:
c

array([2, 2, 2, 2, 4, 4, 4, 4])

In [77]:
x = np.array([10])
d = a+x
d

array([12, 12, 12, 12])

In [102]:
numar= np.array([0,1,2,3,4,5,6,7,8,9,10])
p = numar[numar <=6]

p

array([0, 1, 2, 3, 4, 5, 6])

In [105]:
adad = np.array([0,1,2,3,4,5,6,7,8,9,10])

In [106]:
adad

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
sum_a = np.sum(adad)
sum_a

55

In [116]:
adad2= [   60,  1,  2,  13,  41,  15,  7,  8,  19, 10]
sum_m = np.sort(adad2)
sum_m

array([ 1,  2,  7,  8, 10, 13, 15, 19, 41, 60])

In [126]:
rand_arr = np.random.randint(-10,10,(4,4))
rand_arr

array([[-10,   4,  -2,  -2],
       [ -1,   7,  -2, -10],
       [  0,  -7,  -8,   5],
       [  9,  -3,  -7,   0]])

In [132]:
aa = np.array([1,1,1,1])
bb= np.array([2,2,2,2])
cc= np.vstack((aa,bb,aa,bb))
cc

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [133]:
dd = np.hstack((aa,bb,aa,bb))
dd

array([1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2])

In [134]:
ax = np.array([1,2,3,4,5])
std_ax = np.std(ax)
std_ax

1.4142135623730951

In [135]:
mean_a = np.mean(ax)
mean_a

3.0

In [136]:
norm_a = (a - mean_a)/std_ax
norm_a

array([-0.70710678, -0.70710678, -0.70710678, -0.70710678])